# Generated by Django 3.2.8 on 2022-06-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tarefa', models.IntegerField()),
                ('nome_tarefa', models.CharField(max_length=50)),
                ('data_inicial', models.DateField()),
                ('data_limite', models.DateField()),
                ('hora', models.TimeField()),
                ('status', models.IntegerField(default=0)),
                ('descricao', models.CharField(max_length=250)),
            ],
        ),
    ]
