# Generated by Django 3.2.8 on 2022-06-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='id',
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='id_tarefa',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
